M48
; DRILL file {KiCad 7.0.8} date Tue Dec  5 11:00:01 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-05T11:00:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X137.541Y-136.017
X137.922Y-83.185
X163.449Y-71.501
T2
X152.654Y-71.501
T3
X139.7Y-66.675
X139.7Y-142.875
X165.1Y-66.675
X165.1Y-142.875
T0
M30
