M48
; DRILL file {KiCad 7.0.8} date Mon Nov 27 14:39:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-27T14:39:49-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.01Y-2.815
T2
X5.5Y-2.625
X5.5Y-5.625
X6.5Y-2.625
X6.5Y-5.625
T0
M30
